import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright-core';
import { createApp } from '../server/app.ts';
import { source, holidayImport } from './fixtures.ts';
import { servePages } from './static-server.mjs';

test('browser edits, imports, reviews, saves and exports through the actual engine', { timeout: 90000 }, async () => {
  const root = resolve('.'), output = join(root, 'build/verification'); await mkdir(output, { recursive: true });
  const pages = process.env.MANAGER_TEST_MODE === 'pages';
  const app = pages ? await servePages() : await createApp({ root, dataDirectory: await mkdtemp(join(tmpdir(), 'calendar-browser-test-')) });
  if (!pages) await new Promise(ok => app.server.listen(0, '127.0.0.1', ok));
  const url = pages ? app.url : `http://127.0.0.1:${app.server.address().port}`;
  const browser = await chromium.launch(process.env.CHROME_BIN ? { executablePath: process.env.CHROME_BIN, headless: true } : { channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  page.setDefaultTimeout(10000); const errors = []; page.on('pageerror', error => errors.push(String(error)));
  if (pages) page.on('request', request => { if (new URL(request.url()).pathname.includes('/api/')) errors.push(`Unexpected server dependency: ${request.url()}`); });
  const nav = name => page.getByRole('navigation').getByRole('button', { name });
  const addDraft = () => page.getByRole('button', { name: 'Add to draft', exact: true }).click();
  try {
    await page.goto(url);
    await page.getByRole('heading', { name: 'Begin with the publication.' }).waitFor();
    await page.screenshot({ path: join(output, 'overview-empty.png'), fullPage: true });
    await page.getByRole('button', { name: 'Add first source' }).click();
    await page.getByLabel(/^Source ID/).fill(source.id);
    await page.getByLabel('Publication title', { exact: true }).fill(source.title);
    await page.getByLabel('Issuing authority / publisher', { exact: true }).fill(source.publisher);
    await page.getByLabel('Public URL', { exact: true }).fill(source.url);
    await addDraft();
    await nav('Events').click(); await page.getByRole('button', { name: '+ Add event', exact: true }).click();
    await page.getByLabel('Event ID', { exact: true }).fill('test-lent');
    await page.getByLabel('Event kind', { exact: true }).selectOption('traditional');
    await page.getByLabel('English name', { exact: true }).fill('Test lunar event');
    await page.getByLabel('Khmer name', { exact: true }).fill('សាកល្បង');
    await page.getByLabel(/^Sources/).selectOption(source.id);
    await page.getByLabel('Date method', { exact: true }).selectOption('khmer_lunar');
    await page.getByLabel('Lunar month', { exact: true }).selectOption('7');
    await page.getByLabel('Phase', { exact: true }).selectOption('false');
    await page.getByLabel('Asadh policy', { exact: true }).selectOption('ordinary_or_second_asadh');
    await addDraft();

    await page.getByRole('button', { name: '+ Add event', exact: true }).click();
    await page.getByLabel('Event ID', { exact: true }).fill('test-history');
    await page.getByLabel('Event kind', { exact: true }).selectOption('historical');
    await page.getByLabel('English name', { exact: true }).fill('Test historical event');
    await page.getByLabel('Khmer name', { exact: true }).fill('សាកល្បង');
    await page.getByLabel(/^Sources/).selectOption(source.id);
    await page.getByLabel(/^Original historical date/).fill('1920-09-24');
    await page.getByLabel(/^Event dates/).fill('1920-09-24');
    await addDraft();
    await page.locator('article').filter({ hasText: 'Test historical event' }).getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByLabel('Date method', { exact: true }).selectOption('solar');
    await page.getByLabel('Gregorian month', { exact: true }).fill('9');
    await page.getByLabel('Day of month', { exact: true }).fill('24');
    await page.getByRole('button', { name: 'Update draft', exact: true }).click();

    await nav('Import data').click();
    await page.getByLabel('Selected year').fill('2026'); await page.getByRole('button', { name: 'View', exact: true }).click();
    await page.getByLabel('Import content', { exact: true }).fill(holidayImport());
    await page.getByRole('button', { name: 'Review import', exact: true }).click();
    await page.getByRole('button', { name: 'Apply import to draft', exact: true }).click();
    const amendment = JSON.parse(holidayImport()); amendment.holidays[0].dates = ['2026-07-31'];
    await page.getByLabel('Import content', { exact: true }).fill(JSON.stringify(amendment));
    await page.getByRole('button', { name: 'Review import', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Apply import to draft', exact: true }).isDisabled(), true);
    await page.locator('.change-list summary').first().click();
    await page.screenshot({ path: join(output, 'import-review.png'), fullPage: true });
    await page.getByRole('checkbox', { name: /I reviewed the replacements/ }).check();
    await page.getByRole('button', { name: 'Apply import to draft', exact: true }).click();

    await nav('Corrections').click(); await page.getByRole('button', { name: '+ Add correction', exact: true }).click();
    await page.getByLabel('Recurring event', { exact: true }).selectOption('test-lent');
    await page.getByLabel('Anchor year', { exact: true }).fill('2026');
    await page.getByLabel('Supporting source', { exact: true }).selectOption(source.id);
    await page.getByLabel(/^Replacement dates/).fill('2026-07-31');
    await page.getByLabel('Reason', { exact: true }).fill('Synthetic browser-test correction');
    await addDraft();
    await nav(/^Review & export/).click();
    await page.getByLabel('Change note', { exact: true }).fill('Browser workflow test');
    await page.getByRole('button', { name: 'Save reviewed changes', exact: true }).click();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Prepare export', exact: true }).click();
    const [dataDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Download data JSON', exact: true }).click()]);
    await dataDownload.saveAs(join(output, 'data.json'));
    const [manifestDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Download manifest', exact: true }).click()]);
    await manifestDownload.saveAs(join(output, 'manifest.json'));
    const bytes = await readFile(join(output, 'data.json')), exported = JSON.parse(bytes.toString());
    const manifest = JSON.parse(await readFile(join(output, 'manifest.json'), 'utf8'));
    assert.equal(manifest.sha256, createHash('sha256').update(bytes).digest('hex'));
    assert.equal(exported.events.find(e => e.id === 'test-history').originalDate, '1920-09-24');
    assert.equal(exported.overrides.length, 1);
    assert.equal(exported.holidayCalendars[0].holidays[0].dates[0], '2026-07-31');
    await page.reload();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await page.getByLabel('Selected year').fill('2026'); await page.getByRole('button', { name: 'View', exact: true }).click();
    assert.equal(await page.locator('tbody tr').count(), 3);
    assert.equal(await page.getByText('2026-07-31', { exact: true }).count(), 2);
    await page.screenshot({ path: join(output, 'overview-with-data.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: join(output, 'mobile.png'), fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
  } catch (error) { await page.screenshot({ path: join(output, 'failure.png'), fullPage: true }); throw error; }
  finally { await browser.close(); await app.close(); }
});
