import { navigate, openSection } from './ui-helpers.mjs';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright-core';
import { createApp } from '../server/app.ts';
import { source, holidayImport } from './fixtures.ts';
import { servePages } from './static-server.mjs';

test('browser generates a year, saves unfinished work, corrects dates and confirms a publication', { timeout: 90000 }, async () => {
  const root = resolve('.'), output = join(root, 'build/verification'); await mkdir(output, { recursive: true });
  const pages = process.env.MANAGER_TEST_MODE === 'pages';
  const app = pages ? await servePages() : await createApp({ root, dataDirectory: await mkdtemp(join(tmpdir(), 'calendar-year-test-')) });
  if (!pages) await new Promise(ok => app.server.listen(0, '127.0.0.1', ok));
  const url = pages ? app.url : `http://127.0.0.1:${app.server.address().port}`;
  const browser = await chromium.launch(process.env.CHROME_BIN ? { executablePath: process.env.CHROME_BIN, headless: true } : { channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  page.setDefaultTimeout(10000); const errors = []; page.on('pageerror', e => errors.push(String(e)));
  try {
    await page.goto(url);
    await page.getByRole('textbox', { name: 'Search calendar', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Overview', exact: true }).count(), 0);
    await page.getByLabel('Selected year').selectOption('2027');
    await page.getByRole('button', { name: 'Generate year', exact: true }).click();
    assert.equal(await page.locator('.record-list article').count(), 16);
    assert.equal(await page.getByRole('button', { name: 'Generate year', exact: true }).count(), 0);
    assert.equal(await page.getByRole('banner').getByRole('navigation').count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Tools', exact: true }).count(), 0);
    assert.equal(await page.getByRole('dialog').count(), 0);
    await navigate(page, 'Review & save');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await navigate(page, 'Export');
    assert.equal(await page.getByRole('button', { name: 'Prepare export', exact: true }).isDisabled(), true);
    await page.reload();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await navigate(page, 'Calendar');
    await page.getByLabel('Selected year').selectOption('2027');

    await page.getByLabel('PDF or photo', { exact: true }).setInputFiles({ name: 'test-announcement.png', mimeType: 'image/png', buffer: await readFile('public/icons/khmer-calendar.png') });
    assert.equal(await page.getByAltText('Government announcement preview').evaluate(async img => { await img.decode(); return img.naturalWidth; }), 512);
    await navigate(page, 'Review & save');
    await navigate(page, 'Calendar');
    assert.equal(await page.getByRole('button', { name: 'Hide announcement', exact: true }).count(), 0);
    assert.equal(await page.getByAltText('Government announcement preview').isVisible(), true);
    const newYearRow = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Khmer New Year', exact: true }) });
    const editHoliday = newYearRow.getByRole('button', { name: 'Edit', exact: true });
    await editHoliday.scrollIntoViewIfNeeded();
    const scrollBeforeEdit = await page.evaluate(() => scrollY);
    await editHoliday.click();
    const dialog = page.getByRole('dialog', { name: 'Edit holiday', exact: true });
    await dialog.waitFor();
    assert.equal(await dialog.evaluate(el => el.contains(document.activeElement)), true);
    assert.equal(await page.evaluate(() => scrollY), scrollBeforeEdit);
    await page.getByLabel('English name', { exact: true }).fill('Discard this unsaved edit');
    await page.keyboard.press('Escape');
    await dialog.waitFor({ state: 'detached' });
    assert.equal(await editHoliday.evaluate(el => el === document.activeElement), true);
    assert.equal(await page.evaluate(() => scrollY), scrollBeforeEdit);
    assert.equal(await newYearRow.getByRole('heading', { name: 'Khmer New Year', exact: true }).count(), 1);
    await editHoliday.click();
    await page.getByLabel('Holiday dates', { exact: true }).fill('2027-02-30');
    await page.getByRole('button', { name: 'Update draft', exact: true }).click();
    await dialog.getByRole('alert').filter({ hasText: 'not a real Gregorian date' }).waitFor();
    assert.equal(await page.getByLabel('Holiday dates', { exact: true }).inputValue(), '2027-02-30');
    await page.getByLabel('Holiday dates', { exact: true }).fill('2027-04-15..2027-04-17');
    await page.getByRole('button', { name: 'Update draft', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    await page.locator('article').filter({ has: page.getByRole('heading', { name: 'Water Festival', exact: true }) }).getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByRole('button', { name: 'Remove record', exact: true }).click();
    await page.getByRole('button', { name: '+ Add holiday', exact: true }).click();
    await page.getByRole('dialog', { name: 'Add holiday', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Close editor', exact: true }).click();
    assert.equal(await page.getByRole('dialog').count(), 0);
    await page.getByRole('button', { name: '+ Add holiday', exact: true }).click();
    await page.screenshot({ path: join(output, `${pages ? 'pages-' : ''}holiday-popup.png`) });
    await page.setViewportSize({ width: 390, height: 844 });
    const addDialog = page.getByRole('dialog', { name: 'Add holiday', exact: true });
    const box = await addDialog.boundingBox();
    assert.ok(box.x >= 0 && box.x + box.width <= 390 && box.y >= 0 && box.y + box.height <= 844);
    assert.equal(await addDialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await page.getByRole('button', { name: 'Cancel', exact: true }).focus();
    await page.keyboard.press('Tab');
    assert.equal(await addDialog.evaluate(el => el.contains(document.activeElement)), true);
    await addDialog.locator('.dialog-content').evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: join(output, `${pages ? 'pages-' : ''}holiday-popup-mobile.png`) });
    await page.setViewportSize({ width: 1440, height: 1080 });
    await page.getByLabel('Holiday ID', { exact: true }).fill('test-extra');
    await page.getByLabel('English name', { exact: true }).fill('Synthetic extra holiday');
    await page.getByLabel('Khmer name', { exact: true }).fill('សាកល្បង');
    await page.getByLabel('Holiday dates', { exact: true }).fill('2027-07-01');
    await page.getByRole('button', { name: 'Add to draft', exact: true }).click();
    await navigate(page, 'Review & save');
    await page.getByRole('button', { name: 'Confirm 2027', exact: true }).click();
    await page.getByRole('dialog', { name: 'Confirm year', exact: true }).getByRole('button', { name: '+ Add reference', exact: true }).click();
    await page.getByRole('dialog', { name: 'Add reference', exact: true }).waitFor();
    await page.getByLabel(/^Source ID/).fill(source.id);
    await page.getByLabel('Publication title', { exact: true }).fill(source.title);
    await page.getByLabel('Issuing authority / publisher', { exact: true }).fill(source.publisher);
    await page.getByLabel('Public URL', { exact: true }).fill(source.url);
    await page.getByRole('button', { name: 'Add to draft', exact: true }).click();
    await page.getByRole('dialog', { name: 'Confirm year', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Keep editing', exact: true }).click();
    assert.equal(await page.evaluate(() => document.body.style.overflow), '');
    await navigate(page, 'Calendar');
    assert.equal(await page.getByRole('textbox', { name: 'Search calendar', exact: true }).isVisible(), true);
    assert.equal(await page.getByAltText('Government announcement preview').count(), 1);
    // Changing status must retain a source selected in the optional details.
    await editHoliday.click();
    await openSection(page, 'Sources & other details');
    await page.getByLabel('Government sources', { exact: true }).selectOption(source.id);
    await page.getByLabel('Status', { exact: true }).selectOption('active');
    assert.deepEqual(await page.getByLabel('Government sources', { exact: true }).evaluate(el => [...el.selectedOptions].map(o => o.value)), [source.id]);
    await page.getByLabel('Status', { exact: true }).selectOption('draft');
    assert.deepEqual(await page.getByLabel('Government sources', { exact: true }).evaluate(el => [...el.selectedOptions].map(o => o.value)), [source.id]);
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await navigate(page, 'Calendar');
    await navigate(page, 'Review & save');
    await page.getByRole('button', { name: 'Confirm 2027', exact: true }).click();
    await page.getByRole('dialog', { name: 'Confirm year', exact: true }).waitFor();
    await page.getByLabel('Publication checked', { exact: true }).selectOption(source.id);
    assert.equal(await page.getByRole('button', { name: 'Confirm reviewed year', exact: true }).isDisabled(), true);
    await page.getByRole('checkbox', { name: /I checked the holidays/ }).check();
    await page.getByRole('button', { name: 'Confirm reviewed year', exact: true }).click();
    assert.equal(await page.locator('article .badge').filter({ hasText: 'Awaiting review' }).count(), 0);
    await page.screenshot({ path: join(output, `${pages ? 'pages-' : ''}generated-year.png`), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: join(output, `${pages ? 'pages-' : ''}generated-year-mobile.png`), fullPage: true });
    await navigate(page, 'Review & save');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await page.getByText('Saved · revision 2', { exact: true }).waitFor();
    await navigate(page, 'Export');
    await page.getByRole('button', { name: 'Prepare export', exact: true }).click();
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Download data JSON', exact: true }).click()]);
    const data = JSON.parse(await readFile(await download.path(), 'utf8')), holidays = data.holidayCalendars[0].holidays;
    assert.deepEqual(holidays.find(h => h.id === 'khmer-new-year').dates, ['2027-04-15', '2027-04-16', '2027-04-17']);
    assert.ok(!holidays.some(h => h.id === 'water'));
    assert.ok(holidays.some(h => h.id === 'test-extra'));
    assert.ok(holidays.every(h => h.status === 'active' && h.sourceIds.includes(source.id)));
    assert.deepEqual(errors, []);
  } finally { await browser.close(); if (pages) await app.close(); else await new Promise(ok => app.server.close(ok)); }
});

test('browser edits, imports, reviews, saves and exports through the actual engine', { timeout: 90000 }, async () => {
  const root = resolve('.'), output = join(root, 'build/verification'); await mkdir(output, { recursive: true });
  const pages = process.env.MANAGER_TEST_MODE === 'pages';
  const app = pages ? await servePages() : await createApp({ root, dataDirectory: await mkdtemp(join(tmpdir(), 'calendar-browser-test-')) });
  if (!pages) await new Promise(ok => app.server.listen(0, '127.0.0.1', ok));
  const url = pages ? app.url : `http://127.0.0.1:${app.server.address().port}`;
  const browser = await chromium.launch(process.env.CHROME_BIN ? { executablePath: process.env.CHROME_BIN, headless: true } : { channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  page.setDefaultTimeout(10000); const errors = []; page.on('pageerror', error => errors.push(String(error)));
  if (pages) page.on('request', request => { if (new URL(request.url()).pathname.includes('/api/')) errors.push(`Unexpected server dependency: ${request.url()}`); });
  const addDraft = () => page.getByRole('button', { name: 'Add to draft', exact: true }).click();
  try {
    await page.goto(url);
    await page.getByRole('textbox', { name: 'Search calendar', exact: true }).waitFor();
    await page.screenshot({ path: join(output, 'calendar-empty.png'), fullPage: true });
    await page.getByRole('button', { name: '+ Add event', exact: true }).click();
    await page.getByLabel('Event ID', { exact: true }).fill('test-lent');
    await page.getByLabel('Event kind', { exact: true }).selectOption('traditional');
    await page.getByLabel('English name', { exact: true }).fill('Test lunar event');
    await page.getByLabel('Khmer name', { exact: true }).fill('សាកល្បង');
    await page.getByRole('button', { name: '+ Add reference', exact: true }).click();
    const referenceDialog = page.getByRole('dialog', { name: 'Add reference', exact: true });
    await referenceDialog.getByLabel(/^Source ID/).fill(source.id);
    await referenceDialog.getByLabel('Source kind', { exact: true }).selectOption('government');
    await referenceDialog.getByLabel('Publication title', { exact: true }).fill(source.title);
    await referenceDialog.getByLabel('Issuing authority / publisher', { exact: true }).fill(source.publisher);
    await referenceDialog.getByLabel('Public URL', { exact: true }).fill(source.url);
    await referenceDialog.getByRole('button', { name: 'Add to draft', exact: true }).click();
    await referenceDialog.waitFor({ state: 'detached' });
    assert.equal(await page.getByLabel('English name', { exact: true }).inputValue(), 'Test lunar event');
    assert.deepEqual(await page.getByLabel('Sources', { exact: true }).evaluate(el => [...el.selectedOptions].map(o => o.value)), [source.id]);
    await page.getByLabel('Date method', { exact: true }).selectOption('khmer_lunar');
    await page.getByLabel('Lunar month', { exact: true }).selectOption('7');
    await page.getByLabel('Phase', { exact: true }).selectOption('false');
    await page.getByLabel('Asadh policy', { exact: true }).selectOption('ordinary_or_second_asadh');
    await addDraft();

    await page.getByRole('button', { name: '+ Add event', exact: true }).click();
    await page.getByLabel('Event ID', { exact: true }).fill('test-history');
    await page.getByLabel('Event kind', { exact: true }).selectOption('historical');
    await page.getByLabel('English name', { exact: true }).fill('Test historical event');
    await page.getByLabel('Khmer name', { exact: true }).fill('សាកល្បង');
    await page.getByLabel(/^Sources/).selectOption(source.id);
    await page.getByLabel(/^Original historical date/).fill('1920-09-24');
    await page.getByLabel(/^Event dates/).fill('1920-09-24');
    await addDraft();
    await page.locator('article').filter({ hasText: 'Test historical event' }).getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByLabel('Date method', { exact: true }).selectOption('solar');
    await page.getByLabel('Gregorian month', { exact: true }).fill('9');
    await page.getByLabel('Day of month', { exact: true }).fill('24');
    await page.getByRole('button', { name: 'Update draft', exact: true }).click();

    await page.getByLabel('Selected year').selectOption('2026');
    await page.getByRole('button', { name: 'Import', exact: true }).click();
    await page.getByRole('dialog', { name: 'Import data', exact: true }).waitFor();
    await page.getByLabel('Import content', { exact: true }).fill(holidayImport());
    await page.getByRole('button', { name: 'Review import', exact: true }).click();
    await page.getByRole('button', { name: 'Apply import', exact: true }).click();
    await page.getByRole('button', { name: 'Import', exact: true }).click();
    const amendment = JSON.parse(holidayImport()); amendment.holidays[0].dates = ['2026-07-31'];
    await page.getByLabel('Import content', { exact: true }).fill(JSON.stringify(amendment));
    await page.getByRole('button', { name: 'Review import', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Apply import', exact: true }).isDisabled(), true);
    await page.locator('.change-list summary').first().click();
    await page.screenshot({ path: join(output, 'import-review.png'), fullPage: true });
    await page.getByRole('checkbox', { name: /I reviewed the replacements/ }).check();
    await page.getByRole('button', { name: 'Apply import', exact: true }).click();

    await page.locator('article').filter({ hasText: 'Test lunar event' }).getByRole('button', { name: 'Edit', exact: true }).click();
    await openSection(page, 'Change dates for a specific year');
    await page.getByRole('button', { name: 'Change 2026 dates', exact: true }).click();
    await page.getByLabel('Anchor year', { exact: true }).fill('2026');
    await page.getByLabel('Supporting source', { exact: true }).selectOption(source.id);
    await page.getByLabel(/^Replacement dates/).fill('2026-07-31');
    await page.getByLabel('Reason', { exact: true }).fill('Synthetic browser-test correction');
    await page.getByRole('dialog', { name: 'Change event dates', exact: true }).getByRole('button', { name: 'Add to draft', exact: true }).click();
    await page.getByRole('dialog', { name: 'Edit event', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click();
    await navigate(page, 'Review & save');
    await page.getByLabel('Change note', { exact: true }).fill('Browser workflow test');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await navigate(page, 'Export');
    await page.getByRole('button', { name: 'Prepare export', exact: true }).click();
    const [dataDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Download data JSON', exact: true }).click()]);
    await dataDownload.saveAs(join(output, 'data.json'));
    const [manifestDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Download manifest', exact: true }).click()]);
    await manifestDownload.saveAs(join(output, 'manifest.json'));
    const bytes = await readFile(join(output, 'data.json')), exported = JSON.parse(bytes.toString());
    const manifest = JSON.parse(await readFile(join(output, 'manifest.json'), 'utf8'));
    assert.equal(manifest.sha256, createHash('sha256').update(bytes).digest('hex'));
    assert.equal(exported.events.find(e => e.id === 'test-history').originalDate, '1920-09-24');
    assert.equal(exported.overrides.length, 1);
    assert.equal(exported.holidayCalendars[0].holidays[0].dates[0], '2026-07-31');
    await page.reload();
    await page.getByText('Saved · revision 1', { exact: true }).waitFor();
    await page.getByLabel('Selected year').selectOption('2026');
    assert.equal(await page.locator('.calendar-list article').count(), 3);
    assert.equal(await page.locator('time[datetime="2026-07-31"]').count(), 2);
    await page.getByLabel('Calendar filter', { exact: true }).selectOption('event');
    assert.equal(await page.locator('.calendar-list article').count(), 2);
    await page.getByLabel('Search calendar', { exact: true }).fill('lunar');
    assert.equal(await page.locator('.calendar-list article').count(), 1);
    await page.getByLabel('Search calendar', { exact: true }).fill('');
    await page.getByLabel('Calendar filter', { exact: true }).selectOption('all');
    await page.screenshot({ path: join(output, 'overview-with-data.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: join(output, 'mobile.png'), fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
  } catch (error) { await page.screenshot({ path: join(output, 'failure.png'), fullPage: true }); throw error; }
  finally { await browser.close(); await app.close(); }
});
